// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    T: typeof import('./src/T.vue')['default']
    TButton: typeof import('./src/TButton.vue')['default']
    TCheckbox: typeof import('./src/TCheckbox.vue')['default']
    TContainer: typeof import('./src/TContainer.vue')['default']
    TInput: typeof import('./src/TInput.vue')['default']
    TTheme: typeof import('./src/TTheme.vue')['default']
  }
}

export { }
